export const SET_LISTS = 'SET_LISTS';
export const FETCH_LISTS = 'FETCH_LISTS';
export const CREATE_LIST = 'CREATE_LIST';
export const UPLOAD_NEW_LIST = 'UPLOAD_NEW_LIST';
export const REQUEST_DELETE_LIST = 'REQUEST_DELETE_LIST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';

export const SET_SELECTED_LIST_ID  = 'SET_SELECTED_LIST_ID ';

export const SET_TASKS = 'SET_TASKS';
export const FETCH_TASKS = 'FETCH_TASKS';
export const NEW_TASK = 'NEW_TASK';
export const UPLOAD_NEW_TASK = 'UPLOAD_NEW_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const RESET_TASKS = 'RESET_TASKS';